### ISSUE TITLE
Question about Weighted Stack

### ISSUE THREAD

**Issue by kutsin** [nathantannar4/Turbocharger#2]
Hi, first of all I would like to say thank you for this lib, I like it very much.

I wondering, if its possible to make an improvement to Weighted Stack, to add them ability to place some self sized subviews along with those with weights. For example if i pass -1 or 0 weight, it would mean that this view should have its own size. 

You can say that its possible to place such views just outside this stack, but there are some cases for example  when i have a collection of generic views and i dont know their type and order.

I dont ask you to do it, i just trying to figure out how to solve this by myself without performance issues, may be you could give me some advice

Thank you again

**Comment by nathantannar4** [comment]
Thanks for showing your appreciation! 

What you're trying to achieve is either really simple or more tricky. For example, if you can use an `HStack` with a `WeightedHStack` embedded within. This way the `Text` views will have their own size.

<img width="1423" alt="image" src="https://github.com/nathantannar4/Turbocharger/assets/15272998/cd4b3762-78d2-428a-953a-e3af6b14cb6f">

However, if what you are trying to achieve is this:

```swift
WeightedHStack(spacing: 0) {
    Color.blue

    Text("Hello, World").layoutWeightPriority(0)

    Color.red
}
```

Then it would require some custom layout that is similar  `WeightedHStackLayout` to support that. Generally I have not found myself needed such a layout, so I never thought to build support for it.

Instead, I generally do something like this:

```swift
HStack(spacing: 0) {
    Color.blue
        .frame(maxWidth: .infinity)

    Text("Hello, World")

    Color.red
        .frame(maxWidth: .infinity)
}
```

**Comment by kutsin** [comment]
I think, I have a bit more tricky case: 
<img width="898" alt="Screenshot" src="https://github.com/nathantannar4/Turbocharger/assets/14885155/37503226-a024-4ad1-85c5-7cb26387ec3a">

Some real world example of how I guess I would use it:
<img width="553" alt="Screenshot 2024-01-16 at 6 22 28 PM" src="https://github.com/nathantannar4/Turbocharger/assets/14885155/c5417b07-4fb6-47b8-934f-8c1d2cc39f7e">
