### ISSUE TITLE
Build failure on Xcode 15.3 RC

### ISSUE THREAD

**Issue by danqing** [nathantannar4/Turbocharger#3]
Doesn't happen on earlier Xcode versions:

![CleanShot 2024-02-27 at 11 07 09@2x](https://github.com/nathantannar4/Turbocharger/assets/5134133/de310624-0569-4302-8935-2ccbf0d34dc5)

**Comment by nathantannar4** [comment]
Fixed in `1.1.3`. Seems like a change to the Swift compiler that broke some type inference (or maybe it wasnt supposed to work as it did previously)
